# Generated by Django 4.1.7 on 2023-02-21 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacaapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='comments',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
