# Generated by Django 4.1.7 on 2023-04-01 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacaapp', '0002_attendance_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='resdual_vacations',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
